force-app/main/default/objects/ChatGPTCallout__c/ChatGPTCallout__c.object-meta.xml
<CustomObject>
    <label>Chat GPT Callout</label>
    <nameField>
        <displayFormat>Callout-{0000}</displayFormat>
        <label>ChatGPTCallout Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chat GPT Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChatGPTCallout__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Finish_Probability__c.field-meta.xml
<CustomField>
    <fullName>Finish_Probability__c</fullName>
    <label>Finish Probability</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Input_Token_Count__c.field-meta.xml
<CustomField>
    <fullName>Input_Token_Count__c</fullName>
    <label>Input Token Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Max_Number_of_Tokens__c.field-meta.xml
<CustomField>
    <fullName>Max_Number_of_Tokens__c</fullName>
    <label>Max Number of Tokens</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Output_Token_Count__c.field-meta.xml
<CustomField>
    <fullName>Output_Token_Count__c</fullName>
    <label>Output Token Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Request_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Request_Timestamp__c</fullName>
    <label>Request Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Response_index__c.field-meta.xml
<CustomField>
    <fullName>Response_index__c</fullName>
    <label>Response index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Response_Text__c.field-meta.xml
<CustomField>
    <fullName>Response_Text__c</fullName>
    <label>Response Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Response_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Response_Timestamp__c</fullName>
    <label>Response Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Satus__c.field-meta.xml
<CustomField>
    <fullName>Satus__c</fullName>
    <label>Satus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Screen Flow</fullName>
            </value>
            <value>
                <fullName>UI Component</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/Text_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Text_Prompt__c</fullName>
    <description>Text</description>
    <label>Text Prompt</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ChatGPTCallout__c/fields/User_IP__c.field-meta.xml
<CustomField>
    <fullName>User_IP__c</fullName>
    <label>User IP</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChatGPTCalloutLogger.cls
public without sharing class ChatGPTCalloutLogger {
  public List<ChatGPTCallout__c> logs;
  private static ChatGPTCalloutLogger instance;

  private ChatGPTCalloutLogger() {
    logs = new List<ChatGPTCallout__c>();
  }

  public static ChatGPTCalloutLogger getInstance() {
    instance = instance != null ? instance : new ChatGPTCalloutLogger();
    return instance;
  }

  public Boolean addLog(ChatGPTCallout__c log) {
    this.logs.add(log);

    return true;
  }

  public List<ChatGPTCallout__c> getLogs() {
    return this.logs;
  }

  /**
   * Logs the ChatGPT callout on a custom object for analysis and tracking purposes.
   * @param prompt The prompt sent in the API request.
   * @param maxTokens The number of tokens for the API response.
   * @param responseWrapper The AIResponseWrapper containing the response from the OpenAI API.
   * @param isSuccess A boolean indicating whether the callout was successful.
   * @param errorMessage Any error message encountered during the callout (if applicable).
   * @param userIP The IP address of the user making the API call.
   */
  public static ChatGPTCallout__c logChatGPTCallout(
    String prompt,
    Integer maxTokens,
    ChatGPTCallout.AIResponseWrapper responseWrapper,
    HttpResponse response,
    Datetime requestTimestamp,
    String source
  ) {
    ChatGPTCallout__c calloutLog = new ChatGPTCallout__c();

    // Logging the request details
    calloutLog.Request_Timestamp__c = requestTimestamp;
    calloutLog.Input_Token_Count__c = prompt?.split(' ').size();
    calloutLog.Text_Prompt__c = prompt;
    calloutLog.Max_Number_of_Tokens__c = maxTokens;
    calloutLog.Source__c = source;

    // Logging the response details (if available)
    if (
      responseWrapper != null &&
      responseWrapper.choices != null &&
      !responseWrapper.choices.isEmpty()
    ) {
      ChatGPTCallout.AIChoice firstChoice = responseWrapper.choices.get(0);
      calloutLog.Response_Timestamp__c = Datetime.now();
      calloutLog.Response_Text__c = firstChoice.text;
      calloutLog.Output_Token_Count__c = firstChoice.text?.split(' ').size();
      calloutLog.Finish_Probability__c = firstChoice.finishProbability;
      calloutLog.Response_index__c = firstChoice.index;
    }

    // Logging status and error (if applicable)
    calloutLog.Satus__c = response.getStatusCode() >= 400 ? 'Error' : 'Success';
    //calloutLog.Error_Message__c =  response.getStatusCode() >= 400 ? response.getBody().substring(0, 250) : '';

    // Logging the user IP
    calloutLog.User_IP__c = [
      SELECT Id, SourceIp
      FROM AuthSession
      WHERE UsersId = :UserInfo.getUserId()
      ORDER BY CreatedDate DESC
      LIMIT 1
    ]
    .SourceIp;
    //logs.add(calloutLog);

    return calloutLog;
  }
}